In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel("Netflix_Unclean_Project.xlsx")

In [3]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [4]:
df.shape

(1013, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   object
 1   Customer_Name      1013 non-null   object
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   object
 4   Content_Type       1013 non-null   object
 5   Genre              1010 non-null   object
 6   Country            1013 non-null   object
 7   Subscription_Plan  1013 non-null   object
 8   Device             1009 non-null   object
 9   Payment_Method     1008 non-null   object
 10  Account_Status     1013 non-null   object
 11  Join_Date          1013 non-null   datetime64[ns]
 12  Last_Watch_Date    1013 non-null   datetime64[ns]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(10)
memory usage: 158.4+ KB

In [6]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612096,2024-11-27 19:59:45.784797696,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [7]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [12]:
df.replace(["NULL","N/A",""," "],np.nan,inplace=True)

In [13]:
df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)

In [14]:
df["Subscription_Plan"].value_counts()

Subscription_Plan
Premium     353
Standard    327
Basic       324
STANDARD      3
BASIC         1
Name: count, dtype: int64

In [15]:
df["Title"]=df["Title"].str.title()
df["Content_Type"]=df["Content_Type"].str.title()
df["Genre"]=df["Genre"].str.title()
df["Country"]=df["Country"].str.title()
df["Subscription_Plan"]=df["Subscription_Plan"].str.title()
df["Device"]=df["Device"].str.title()
df["Payment_Method"]=df["Payment_Method"].str.title()
df["Account_Status"]=df["Account_Status"].str.title()
df["Customer_Name"]=df["Customer_Name"].str.title()

In [16]:
df["Subscription_Plan"].value_counts()

Subscription_Plan
Premium     353
Standard    330
Basic       325
Name: count, dtype: int64

In [17]:
df["Account_Status"].value_counts()

Account_Status
Active       718
Cancelled    198
Paused        92
Name: count, dtype: int64

In [18]:
cols = ["Watch_Hours","Monthly_Fee","Movies_Watched","Episodes_Watched","Avg_Rating","Monthly_Sessions","Download_Count","Age"]
for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1008 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1008 non-null   object
 1   Customer_Name      1008 non-null   object
 2   Age                1008 non-null   int64
 3   Title              1008 non-null   object
 4   Content_Type       1008 non-null   object
 5   Genre              1004 non-null   object
 6   Country            1007 non-null   object
 7   Subscription_Plan  1008 non-null   object
 8   Device             1004 non-null   object
 9   Payment_Method     1001 non-null   object
 10  Account_Status     1008 non-null   object
 11  Join_Date          1008 non-null   datetime64[ns]
 12  Last_Watch_Date    1008 non-null   datetime64[ns]
 13  Watch_Hours        1008 non-null   float64
 14  Monthly_Fee        1008 non-null   int64
 15  Movies_Watched     1008 non-null   int64
 16  Episodes_Watched   1008 non-null   int64
 17  Avg_Rating         1008 non-null   float64
 18  Monthly_Sessions   1008 non-null   int64
 19  Download_Count     1008 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(10)
memory usage: 165.4+ KB

In [20]:
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
df["Last_Watch_Date"]=pd.to_datetime(df["Last_Watch_Date"],errors="coerce")

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1008 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1008 non-null   object
 1   Customer_Name      1008 non-null   object
 2   Age                1008 non-null   int64
 3   Title              1008 non-null   object
 4   Content_Type       1008 non-null   object
 5   Genre              1004 non-null   object
 6   Country            1007 non-null   object
 7   Subscription_Plan  1008 non-null   object
 8   Device             1004 non-null   object
 9   Payment_Method     1001 non-null   object
 10  Account_Status     1008 non-null   object
 11  Join_Date          1008 non-null   datetime64[ns]
 12  Last_Watch_Date    1008 non-null   datetime64[ns]
 13  Watch_Hours        1008 non-null   float64
 14  Monthly_Fee        1008 non-null   int64
 15  Movies_Watched     1008 non-null   int64
 16  Episodes_Watched   1008 non-null   int64
 17  Avg_Rating         1008 non-null   float64
 18  Monthly_Sessions   1008 non-null   int64
 19  Download_Count     1008 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(10)
memory usage: 165.4+ KB

In [22]:
df=df[(df["Age"]>=18) & (df["Age"]<=100)]

In [23]:
df=df[df["Watch_Hours"]>=0]
df=df[df["Monthly_Fee"]>=0]
df=df[df["Movies_Watched"]>=0]
df=df[df["Episodes_Watched"]>=0]
df=df[df["Avg_Rating"]>=0]
df=df[df["Monthly_Sessions"]>=0]
df=df[df["Download_Count"]>=0]

In [24]:
df["Watch_Hours"]=df["Watch_Hours"].fillna(df["Watch_Hours"].mean())
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Monthly_Fee"]=df["Monthly_Fee"].fillna(df["Monthly_Fee"].mean())

In [25]:
df["Genre"]=df["Genre"].fillna("Unknown")
df["Device"]=df["Device"].fillna("Unknown")
df["Payment_Method"]=df["Payment_Method"].fillna("Unknown")

In [26]:
df["Customer_Renevue"]=df["Monthly_Fee"]*df["Monthly_Sessions"]

In [27]:
df["Engagement_Score"]=(df["Watch_Hours"]+df["Monthly_Sessions"]+df["Download_Count"])

In [28]:
bins=[0,20,50,100,np.inf]
label=["Low","Medium","High","Very High"]
df["Watch_Category"]= pd.cut(df["Watch_Hours"],bins=bins,labels=label)

In [29]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Renevue,Engagement_Score,Watch_Category
0,CUST10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,28.0,649,5,97,3.6,11,3,7139,42.0,Medium
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,0.0,149,5,84,4.5,22,19,3278,41.0,NaN
2,CUST10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,28.9,149,16,106,3.8,26,3,3874,57.9,Medium
3,CUST10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,27.6,649,10,24,2.6,27,9,17523,63.6,Medium
4,CUST10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,32.0,649,10,78,3.2,15,20,9735,67.0,Medium

In [30]:
bins=[17,25,35,50,100]
label=["18-25","26-35","36-50","51+"]
df["Age_Group"]=pd.cut(df["Age"],bins=bins,labels=label)

In [31]:
df["Active_Flag"]=np.where(df["Account_Status"]=="Active",1,0)

In [32]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Renevue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
0,CUST10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,5,97,3.6,11,3,7139,42.0,Medium,18-25,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,5,84,4.5,22,19,3278,41.0,NaN,36-50,1
2,CUST10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Medium,36-50,0
3,CUST10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
4,CUST10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 995 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        995 non-null    object
 1   Customer_Name      995 non-null    object
 2   Age                995 non-null    int64
 3   Title              995 non-null    object
 4   Content_Type       995 non-null    object
 5   Genre              995 non-null    object
 6   Country            994 non-null    object
 7   Subscription_Plan  995 non-null    object
 8   Device             995 non-null    object
 9   Payment_Method     995 non-null    object
 10  Account_Status     995 non-null    object
 11  Join_Date          995 non-null    datetime64[ns]
 12  Last_Watch_Date    995 non-null    datetime64[ns]
 13  Watch_Hours        995 non-null    float64
 14  Monthly_Fee        995 non-null    int64
 15  Movies_Watched     995 non-null    int64
 16  Episodes_Watched   995 non-null    int64
 17  Avg_Rating         995 non-null    float64
 18  Monthly_Sessions   995 non-null    int64
 19  Download_Count     995 non-null    int64
 20  Customer_Renevue   995 non-null    int64
 21  Engagement_Score   995 non-null    float64
 22  Watch_Category     958 non-null    category
 23  Age_Group          995 non-null    category
 24  Active_Flag        995 non-null    int64
dtypes: category(2), datetime64[ns](2), float64(3), int64(8), object(10)
memory usage: 188.9+ KB

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.isnull().sum()

Customer_ID           0
Customer_Name         0
Age                   0
Title                 0
Content_Type          0
Genre                 0
Country               1
Subscription_Plan     0
Device                0
Payment_Method        0
Account_Status        0
Join_Date             0
Last_Watch_Date       0
Watch_Hours           0
Monthly_Fee           0
Movies_Watched        0
Episodes_Watched      0
Avg_Rating            0
Monthly_Sessions      0
Download_Count        0
Customer_Renevue      0
Engagement_Score      0
Watch_Category       37
Age_Group             0
Active_Flag           0
dtype: int64

In [36]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Renevue,Engagement_Score,Active_Flag
count,995.000000,995,995,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,41.920603,2023-12-16 04:27:44.321607936,2024-11-27 13:52:09.648241152,42.605126,438.396985,18.217085,59.514573,3.754573,16.701508,12.460302,7339.680402,71.766935,0.708543
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.000000,298.000000,11.000000,0.000000
25%,30.000000,2022-12-09 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000,2682.000000,51.200000,0.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,58.000000,3.700000,17.000000,12.000000,5841.000000,71.700000,1.000000
75%,53.000000,2024-12-10 00:00:00,2025-11-12 00:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000,11477.000000,90.050000,1.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000,19470.000000,167.300000,1.000000
std,13.797644,NaN,NaN,23.784772,209.136478,10.085605,34.855299,0.723983,8.280686,7.564557,5344.095657,26.202570,0.454662

In [41]:
df.to_csv("Netflix_Clean_Dataset.csv",index=False)

In [39]:
pip install psycopg2.binary sqlalchemy

Requirement already satisfied: psycopg2.binary in c:\users\sayandeep\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\sayandeep\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
from sqlalchemy import create_engine
username = "postgres"
password= "sayandeep12345"
host= "localhost"
port="5432"
database= "Netflix_Database"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="customers"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"data successfully loaded into table '{table_name}' in database '{database}'.")

data successfully loaded into table 'customers' in database 'Netflix_Database'.